FROM ubuntu:22.04

ARG GITHUB_REPO
ARG GITHUB_TOKEN
ARG LABELS=

RUN mkdir /actions-runner
WORKDIR /actions-runner

ADD https://github.com/actions/runner/releases/download/v2.311.0/actions-runner-linux-arm64-2.311.0.tar.gz .
RUN ["tar", "xzf", "./actions-runner-linux-arm64-2.311.0.tar.gz"]
RUN ["rm", "actions-runner-linux-arm64-2.311.0.tar.gz"]
RUN ./bin/installdependencies.sh

RUN ["useradd", "-ms", "/bin/bash", "runner"]
USER runner
